name: TTA
main: de.Herbystar.TTA.Main
version: 5.3
website: https://github.com/herby2212/TTA
author: Herbystar
loadbefore: [CTSNC, CTSNCPlus, PlayerToggle, MagicMusic, CookieCounter, FakePlayers]
description: Title, Tablist, ActionBar, BossBar, Holo, Ping, Glow API!